<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Allure.Reqnroll" Version="2.15.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.61.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
    <PackageReference Include="nunit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestAutomationShowcase.Configuration\TestAutomationShowcase.Configuration.csproj" />
    <ProjectReference Include="..\TestAutomationShowcase.Core\TestAutomationShowcase.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <None Update="allureConfig.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
  </ItemGroup>

</Project>
